#!/bin/bash -li

dafny="/usr/local/lib/dafny/dafny /timeLimit:20 /compile:0  /allowGlobals /noNLarith /autoTriggers:1 /vcsCores:3"
dafnylong="/usr/local/lib/dafny/dafny /timeLimit:40 /compile:0  /allowGlobals /noNLarith /autoTriggers:1 /vcsCores:3"


### Definition Files 
echo ""
echo "Verifying all definition files"
$dafny types.dfy agents.dfy network.dfy synod.dfy


### Proof Files
echo ""
echo "Verifying proof_validity.dfy"
$dafny proof_validity.dfy

echo ""
echo "Verifying proof_agreement_invariants.dfy"
$dafny proof_agreement_invariants.dfy

echo ""
echo "Verifying proof_axioms.dfy"
$dafny proof_axioms.dfy

echo ""
echo "Verifying proof_helper.dfy"
$dafny proof_helper.dfy

echo ""
echo "Verifying proof_agreement.dfy"
$dafny proof_agreement.dfy

echo "Done"

